name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  PESTER_VERSION: '4.10.1'
  PSSA_VERSION: '1.25.0'

defaults:
  run:
    shell: pwsh

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        sh: [ pwsh, powershell ]
        exclude:
          - os: macos-latest
            sh: powershell
          - os: ubuntu-latest
            sh: powershell
    defaults:
      run:
        shell: ${{ matrix.sh }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Cache
        uses: actions/cache@v5
        id: cache
        with:
          path: './.modules'
          key: ${{ env.PSSA_VERSION }}-${{ env.PESTER_VERSION }}

      - name: Install Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          $modules = '[
            { "Name": "PSScriptAnalyzer", "Version": "${{ env.PSSA_VERSION }}" },
            { "Name": "Pester",           "Version": "${{ env.PESTER_VERSION }}" }
          ]' | ConvertFrom-Json

          $modPath = "$pwd/.modules"
          if (-not (Test-Path -Path $modPath)) {
            $null = New-Item -Path $modPath -ItemType Directory
          }

          foreach ($module in $modules) {
            $null = Save-Module -Name $module.Name -RequiredVersion $module.Version -Repository 'PSGallery' -Path $modPath -Confirm:$false -ErrorAction 'Stop'
          }

      - name: PSScriptAnalyzer
        working-directory: .
        run: |
          $pssa = Import-Module -Name './.modules/PSScriptAnalyzer/${{ env.PSSA_VERSION }}/PSScriptAnalyzer.psd1' -Passthru
          Get-ChildItem -Directory | Invoke-ScriptAnalyzer -EnableExit | Format-Table -AutoSize

      - name: Pester summary
        working-directory: .
        run: |
          $pester = Import-Module -Name './.modules/Pester/${{ env.PESTER_VERSION }}/Pester.psd1' -PassThru
          Invoke-Pester -EnableExit -Show Summary

  release:
    runs-on: 'ubuntu-latest'
    needs: test
    if: github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.gitversion.outputs.MajorMinorPatch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4.7.0
        with:
          versionSpec: '6.x'

      - name: GitVersion
        uses: gittools/actions/gitversion/execute@v4.7.0
        id: gitversion

      - name: Update Module Manifest
        run: |
            $manifest = Get-Content -Path ./PwshZendesk.psd1
            $manifest = $manifest | ForEach-Object {
                $_ -replace "(?<=ModuleVersion\s+=\s+('|`"))[^'`"]+(?=('|`"))", '${{ steps.gitversion.outputs.MajorMinorPatch }}'
            }
            $manifest | Set-Content -Path ./PwshZendesk.psd1

      - name: Commit updated Module Manifest
        run: |
            git add ./PwshZendesk.psd1
            git config user.email "bot@rob-mc.cloud"
            git config user.name "Rob McBot"
            git commit --amend --no-edit
            git push --force
            git tag v${{ steps.gitversion.outputs.MajorMinorPatch }}
            git push --tags --force

      - run: zip -r PwshZendesk.zip . -x .\*/\* -x .\*
        shell: bash

      - uses: actions/upload-artifact@v7
        with:
          name: zip
          path: PwshZendesk.zip

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ steps.gitversion.outputs.MajorMinorPatch }}
          files: PwshZendesk.zip

  gallery:
    runs-on: 'ubuntu-latest'
    needs: release
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v8
        with:
          name: zip
      
      - name: Publish to Powershell Gallery
        env:
          VERSION: ${{ needs.release.outputs.version }}
        run: |
          $existing = Find-PSResource -Repository PSGallery -Name PwshZendesk -Version ${{ env.VERSION }} -ErrorAction Ignore
          if ($existing) {
            'Version already published to PS Gallery'
            $existing | Format-List | Out-String | Write-Error
            exit 1
          }
          unzip PwshZendesk.zip
          Publish-PSResource -Path . -Repository PSGallery -ApiKey '${{ secrets.POWERSHELL_GALLERY_APIKEY }}' -Confirm:$false
